# The Main config file for PluginNonebot

# The server's identifier/name
server-name: "SampleServer"

message:
  # Message format
  # Available variables: text, binary
  # TODO binary is not implemented yet
  format: text

  # Enable PlaceholderAPI support
  # Requires PlaceholderAPI
  # TODO Not implemented yet
  placeholderapi: false

  # Enable Unicode Emoji support
  # May not display properly
  # If disabled all emoji in messages will be erased
  unicode-emoji: false

output:
  # Log level
  # Available levels: (trace), debug, info, warn, error
  level: info

  # Log channel
  # Available channels: console, file
  # TODO Not implemented yet
  channel: console

  # Log file path
  # Only works when channel is set to file
  # Relative path to your server jar
  # TODO Not implemented yet
  file: "logs/"

api:
  # API Rate Limit, based on token bucket algorithm
  rate-limit:
    enabled: false
    frequency: 1
    capacity: 3

connections:
# Connections, can add multiple conntections using the same type
#- ws:   # Websocket, plugin will work as an WS server
#- ws-reverse: # Reversed Websocket, plugin will work as an WS client
#  - ws-reverse-1:
#      # Server address for ws client
#      # Setting this will override the following two settings
#      address: "ws://127.0.0.1:8080/mc/ws"
#      # Reconnect interval in milliseconds
#      reconnect-interval: 10000
#      # Access token
#      token: ''
#
#  - ws-1:
#      # Listening host
#      host: 0.0.0.0
#      # Listening port
#      port: 8081
#      # Heartbeat interval in seconds
#      heartbeat-interval: 30
#      # Access token
#      token: ''