name: PluginNonebot
main: fyi.fyw.mc.pluginnonebot.PluginNonebot
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/McNonebot/PluginNonebot
author: FYWinds
depend:
  - kotlin-stdlib