name: PluginNonebot
main: fyi.fyw.mc.pluginnonebot.PluginNonebot
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/McNonebot/PluginNonebot
author: FYWinds
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}