name: Dev Build
on:
  push:
    branches:
      - dev
      - dev/**
    tags-ignore:
      - '**'


jobs:
  build:
    name: Gradle Dev Build
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/gradle-build-action@v2
      - name: Gradle Build
        run: chmod +x ./gradlew && ./gradlew build
      - name: Set env variables
        run: |
          chmod +x .github/scripts/set_env
          .github/scripts/set_env
      - name: Rename Build
        run: |
          chmod +x .github/scripts/rename_artifact
          .github/scripts/rename_artifact
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: "[CI-${{ env.SHORT_SHA }}]${{ env.PROJECT_NAME }}"
          path: build/libs/*-all.jar
          retention-days: 30
          if-no-files-found: error