name: Publish
on:
  pull_request:
    branches:
      - release
      - release/**
    types: [ closed ]

jobs:
  build:
    uses: ./.github/workflows/build-workflow.yml
  release:
    if: github.event.pull_request.merged == true
    needs: build
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: "build/*all.jar"